module.exports = {
  "ZEC": "Zcash",
  "BTC": "Bitcoin",
  "XBT": "Bitcoin",
  "BLK": "BlackCoin",
  "DASH": "Dash",
  "DOGE": "Dogecoin",
  "XDG": "Dogecoin",
  "XDN": "DigitalNote",
  "ETH": "Ethereum",
  "ETC": "Ethereum Classic",
  "LTC": "Litecoin",
  "XRP": "Ripple",
  "XEM": "NEM",
  "XMR": "Monero",
  "XLM": "Stellar Lumens",
  "STR": "Stellar Lumens",
  "STEEM": "Steem",
  "GNT": "Golem",
  "REP": "Augur",
  "MAID": "MaidSafeCoin",
  "BTS": "BitShares",
  "GNO": "Gnosis",
  "STRAT": "Stratis",
  "NXT": "NXT",
  "BCN": "Bytecoin"
};