# Welcome to Serverless!
service: technews

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: ap-northeast-1

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'

plugins:
  - serverless-offline

functions:
  githubTrend:
    handler: index.githubTrend
    description: tech news API service
    events:
      - http:
          path: github/trend
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                vendor: true
  githubReadme:
    handler: index.githubReadme
    description: get github repo's readme.md file
    events:
      - http:
          path: github/readme/{user}/{repoName}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                user: true
                repoName: true
  coinsPriceByMarket:
    handler: index.coinsPriceByMarket
    description: get coins price in single market
    events:
      - http:
          path: price/market/{market}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                market: true
  coinPrice:
    handler: index.coinPrice
    description: get one coin price in all markets
    events:
      - http:
          path: price/coin/{coin}
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                coin: true